os:
  - osx
language: c
compiler:
  - clang
  - gcc
env:
  - EXTRA=
  - EXTRA=--devel
  - EXTRA=--HEAD
before_install:
  - env
  - brew update
  - brew tap leedm777/homebrew-asterisk
  - brew tap homebrew/dupes
  # upgrade only outdated dependencies
  - comm -12 <(brew deps ./asterisk.rb) <(brew outdated) | xargs brew upgrade
  - brew ls
install:
  - brew install --only-dependencies ./asterisk.rb
script:
  - brew reinstall ./asterisk.rb --verbose --with-dev-mode --with-${CC} ${EXTRA}
